from datetime import datetime
import pytz

def html_email(subject_date_str, sections, tool_of_week=None, hot_take=None):
    # sections: dict {heading -> list of {"title","link","summary","source"}}
    def render_items(items):
        lis = []
        for it in items:
            t = it.get("title","").strip()
            l = it.get("link","#")
            s = it.get("summary","").strip()
            src = it.get("source","").strip()
            lis.append(f"""
              <li style="margin:10px 0;">
                <a href="{l}" style="font-weight:600; text-decoration:none;">{t}</a>
                <div style="font-size:14px; color:#333; margin-top:2px;">{s}</div>
                <div style="font-size:12px; color:#777; margin-top:2px;">Source: {src}</div>
              </li>
            """)
        return "\n".join(lis)

    blocks = []
    for heading, items in sections.items():
        if not items:
            continue
        blocks.append(f"""
          <h2 style="margin:20px 0 8px;">{heading}</h2>
          <ul style="padding-left:18px; margin-top:8px;">
            {render_items(items)}
          </ul>
        """)

    tool_block = ""
    if tool_of_week:
        tool_block = f"""
          <h2 style="margin:24px 0 8px;">🛠️ <b>Tool of the Week</b></h2>
          <p style="margin:6px 0;"><a href="{tool_of_week['link']}" style="font-weight:600; text-decoration:none;">{tool_of_week['title']}</a></p>
          <p style="margin:6px 0; font-size:14px;">{tool_of_week.get('summary','')}</p>
        """

    hot_block = ""
    if hot_take:
        hot_block = f"""
          <h2 style="margin:24px 0 8px;">🔥 <b>Hot Take of the Week</b></h2>
          <p style="margin:6px 0; font-size:14px;">{hot_take}</p>
        """

    return f"""<!doctype html>
<html>
  <body style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif; line-height:1.5; color:#111; max-width:720px; margin:0 auto; padding:24px;">
    <h1 style="margin:0 0 8px;">AI Weekly Digest</h1>
    <div style="color:#666; font-size:14px;">{subject_date_str}</div>
    <p style="margin:18px 0;">A concise, curated roundup of the week’s biggest AI updates. <b>Bold</b> highlights for important bits.</p>
    {''.join(blocks)}
    {tool_block}
    {hot_block}
    <hr style="margin:28px 0; border:none; border-top:1px solid #eee;">
    <div style="color:#888; font-size:12px;">Auto-generated by your GitHub Action. Times shown in your timezone.</div>
  </body>
</html>"""

def subject_line(dt, tz="Asia/Kolkata"):
    tzinfo = pytz.timezone(tz)
    return f"AI Weekly Digest — {dt.astimezone(tzinfo).strftime('%b %d, %Y')}"
